const fs = require('fs');
const crypto = require('crypto');
const path = require('path');

const projectRoot = __dirname;
const handoffDir = path.join(projectRoot, 'handoff');

function hashFile(filepath) {
  const fileBuffer = fs.readFileSync(filepath);
  const hashSum = crypto.createHash('sha256');
  hashSum.update(fileBuffer);
  return hashSum.digest('hex');
}

function walkSync(dir, filelist = []) {
  fs.readdirSync(dir).forEach(file => {
    const dirFile = path.join(dir, file);
    if (fs.statSync(dirFile).isDirectory()) {
      if (!dirFile.includes('.git') && !dirFile.includes('node_modules') && !dirFile.includes('.gemini')) {
        filelist = walkSync(dirFile, filelist);
      }
    } else {
      if (!dirFile.includes('.git') && !dirFile.includes('node_modules') && !dirFile.includes('.gemini')) {
        filelist.push(dirFile);
      }
    }
  });
  return filelist;
}

const files = walkSync(projectRoot);
let csv = 'Path,File category,Production / QA / Data / Backup / Documentation,Size,SHA-256,Last modified,Generated by,Required at runtime,Safe for GitHub,Notes\n';

for (const f of files) {
  const relativePath = path.relative(projectRoot, f).replace(/\\/g, '/');
  let category = 'Unknown';
  let prodType = 'Other';
  let required = 'Yes';
  let safe = 'Yes';
  let notes = '';

  if (relativePath.includes('qa/')) prodType = 'QA';
  else if (relativePath.endsWith('.md') || relativePath.includes('README')) prodType = 'Documentation';
  else if (relativePath.endsWith('.json') || relativePath.includes('history') || relativePath.includes('backups')) prodType = 'Data';
  else if (relativePath.endsWith('.bat') || relativePath.endsWith('.ps1') || relativePath.endsWith('.js') || relativePath.endsWith('.html') || relativePath.endsWith('.css')) prodType = 'Production';

  if (relativePath.includes('state.json') || relativePath.includes('history')) safe = 'No';

  const stat = fs.statSync(f);
  const hash = hashFile(f);
  const modified = stat.mtime.toISOString();

  csv += `"${relativePath}","${category}","${prodType}",${stat.size},${hash},"${modified}","Human","${required}","${safe}","${notes}"\n`;
}

fs.writeFileSync(path.join(handoffDir, '14_FILE_INVENTORY.csv'), csv);
console.log('Generated 14_FILE_INVENTORY.csv');
